### ISSUE TITLE
Set cache=True in jit_module

### ISSUE THREAD

**Issue by aperezhortal** [vlouf/dealias#12]
Hi @vlouf, 

Currently, numba compiles the modules each time that they are imported. This adds a few seconds to the total computation time that can be saved by adding `cache=True` to the `jit_module` directives.

I've tested this in my current setup processing nexrad data and worked out of the box.

If you like the idea of adding the cache, I can prepare a PR with the changes.

**Comment by vlouf** [comment]
Hi @aperezhortal 

Thanks, that's a great idea! Yes please do a PR.

**Comment by vlouf** [comment]
Commit 8b193e4
