### ISSUE TITLE
Large artifacts in dealiasing

### ISSUE THREAD

**Issue by SteepAtticStairs** [vlouf/dealias#14]
Hello there,

I've recently discovered this library, and I've been trying to use it with Py-ART. I've thrown together this code that I assume would be a correct implementation of UNRAVEL:

```python
import matplotlib.pyplot as plt
import numpy as np
import pyart
from pyart.correct import dealias_region_based
from unravel import *


# read in file
radar = pyart.io.read_nexrad_archive('KTLX20130520_201643_V06.gz')

radar = radar.extract_sweeps([1]) # extract velocity sweep

corr_vel = unravel_3D_pyart(radar, velname='velocity', dbzname='reflectivity')
theCorrVel = dealias_region_based(radar)
theCorrVel['data'] = corr_vel # comment this line of code to plot Py-ART's dealiased data instead

radar.add_field('dealiased_velocity', theCorrVel, True)

rmin = radar.fields['dealiased_velocity']['valid_min']
rmax = radar.fields['dealiased_velocity']['valid_max']

fig = plt.figure(figsize=[10, 7])
display = pyart.graph.RadarDisplay(radar)
display.plot('dealiased_velocity', vmin=rmin, vmax=rmax, cmap='pyart_balance')
plt.show()
```
[Here](https://noaa-nexrad-level2.s3.amazonaws.com/2013/05/20/KTLX/KTLX20130520_201643_V06.gz) is a link to the NEXRAD radar file I'm using (`KTLX20130520_201643_V06.gz` - the 2013 Moore tornado). It's a direct download link to the file from NOAA's AWS explorer: https://noaa-nexrad-level2.s3.amazonaws.com/index.html

When I use Py-ART's region based algoritm (`dealias_region_based`), I get a correctly dealiased field:

<img width="450" alt="Screen Shot 2023-01-25 at 6 34 06 PM" src="https://user-images.githubusercontent.com/80776609/214717605-80f27408-94ff-415f-9c4f-bb5faf1a5166.png">

However, when I use UNRAVEL's `unravel_3D_pyart` function, I get large artifacts:

<img width="450" alt="Screen Shot 2023-01-25 at 6 32 45 PM" src="https://user-images.githubusercontent.com/80776609/214717995-47afc037-40c3-4657-89ec-51e1d3a0afe9.png">

Am I using or implementing UNRAVEL incorrectly? If so, could you correct my code? Or is this an issue with the algorithm itself, e.g. it doesn't do well for areas of rotation?

I would appreciate any information you have about this.

**Comment by vlouf** [comment]
Your implementation of Unravel is correct, it just seems to fail on that case (which happens some times). Try using with strategy='long_range', to see if it works better for that specific case:

```python
unravel_3D_pyart(radar, velname='velocity', dbzname='reflectivity', strategy='long_range')
```

Probably on your case study the region_based technique from PyART is going to work better though. Hope it helps!
