### ISSUE TITLE
Problem with masked arrays

### ISSUE THREAD

**Issue by jordanbrook** [vlouf/dealias#15]
Hi Val, 

I'm having some problems with dealiasing level 1 odim files straight off rq0. Here's a minimum example:

```
import pyart
from unravel import dealias
file = '/scratch/kl02/jb2354/christmas/50/50_20231225_103000.pvol.h5'
radar = pyart.aux_io.read_odim_h5(file, file_field_names=True)
out = dealias.unravel_3D_pyart(radar, velname='VRADDH', dbzname='DBZH_CLEAN', nyquist_velocity=31)
```
I get a traceback ending in: NumbaTypeError: Unsupported array type: numpy.ma.MaskedArray.

It seems to me like unravel should be expecting masked arrays. Any advice on what I should do here?

Cheers,
Jordan

**Comment by jordanbrook** [comment]
Hi again, just a note that I was able to get the ```unravel_3d_pyart``` function working by adding ```velocity_reference = velocity_reference.filled(np.nan)``` on line 411 in ```dealias.py```. It seems the ```dealiasing_process_2D``` is outputting a masked array that the numba processes aren't expecting. Hope that helps!

**Comment by vlouf** [comment]
Thanks Jordan, it was a bit more work than initially thought to convert all the masked array into normal numpy ndarray, there was a lot of them!
